### ISSUE TITLE
who teacher could give us a sample for screen+audio on firefox.

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/WebRTC-Scalable-Broadcast#16]
hi,our teacher,muaz
scaleable broadcast is a great job for us.i try my best to write my test code based on https://rtcmulticonnection.herokuapp.com/demos/Scalable-Broadcast.html for screen+audio funciton. i start from this sample,it is just because i want replace video stream with screen stream and i also want to save screen+audio stream to a webm file after stoping the streamming,it is similar with Scalable-Broadcast.html.i change 
                connection.session = {
                    audio: true,
                    video: true,
                    oneway: true
                };
replace video:true with screen:true 
and i could not get screen stream by firefox.
i am not familiar with webrtc.could any leader give me a sample for screen+audio.i am appreciated.
thanks

**Comment by muaz-khan** [comment]
Here is an audio+screen demo which works both on Chrome 50+ (Canary/Beta) and Firefox:
- https://rtcmulticonnection.herokuapp.com/demos/Audio+ScreenSharing.html

For Chrome 50+ (Canary/Beta), it requires this Chrome extension:
- https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture

To use same technique in the [scalable-broadcast demo](https://rtcmulticonnection.herokuapp.com/demos/Scalable-Broadcast.html), please set this object:

``` javascript
connection.session = {
   audio: true,
   screen: true,  // ---- this line MUST be "screen"
   oneway: true
};
```
